version: '3.8'
services:
  web:
    image: hwangjungseok/nestjs-bapull:latest
    ports:
      - "3000:3000"
    env_file:
      - /volume/.env
    restart: always
    volumes:
      - /volume/.env:/app/.env